# Generated by Django 3.1.5 on 2021-02-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0006_auto_20210207_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
