# Generated by Django 3.1.5 on 2021-02-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0008_auto_20210207_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('MODERATION', 'MODERATION'), ('DECLINED', 'DECLINED')], default='MODERATION', max_length=20),
        ),
    ]
