# Generated by Django 3.1.5 on 2021-02-08 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ad', '0010_auto_20210208_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_ads', to=settings.AUTH_USER_MODEL),
        ),
    ]
