# Generated by Django 3.1.5 on 2021-02-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0012_auto_20210209_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
