# Generated by Django 3.1.5 on 2021-02-12 10:43

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0013_auto_20210209_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ad.category'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.IntegerField(default=0, verbose_name='price'),
        ),
    ]
